fido-device-onboard/epid-verification-service

- README.md
- demo/docker-compose.yml
- pom.xml
- src/main/resources/application.properties
Signed-off-by: Behera, Tushar Ranjan <tushar.ranjan.behera@intel.com>
> Prepare for 1.0 release development

- pom.xml
Added  PGP plugin in the base `pom.xml` file for signature verification.
> Added PGP plugin in pom.xml

- pom.xml
Sorted the properties file to easy traceability.
While at it, updated the version of a few dependencies.
Signed-off-by: Behera, Tushar Ranjan <tushar.ranjan.behera@intel.com>
> Sort the properties within POM file

- README.md
- demo/README.md
Updating README files. Includes fixing broken links.
> Updating README files

- pom.xml
Updating dependency version:
Spring-boot 2.4.7 --> 2.4.9
> Updating dependency version

- NOTICE
- README.md
- build/README.md
- demo/docker-compose.yml
- pom.xml
- src/main/resources/application.properties
Version rollover to 1.0 release.
> Version rollover to 1.0 release

- README.md
- demo/docker-compose.yml
- pom.xml
- src/main/resources/application.properties
Version rollover for 1.1 Development.
> Version rollover for 1.1 Development

- README.md
- demo/docker-compose.yml
- pom.xml
- src/main/resources/application.properties
Version rollover to 1.0.1 Development.
> Version rollover to 1.0.1 Development

- README.md
- demo/docker-compose.yml
- pom.xml
- src/main/resources/application.properties
Version rollover to 1.0.1 Release.
> Version rollover to 1.0.1 Release

- pom.xml
Upgrading spring-boot version from 2.5.7 to 2.5.8.
> Upgrading spring-boot version from 2.5.7 to 2.5.8

- README.md
- demo/docker-compose.yml
- pom.xml
- src/main/resources/application.properties
Version rollover to 1.0.2-SNAPSHOT.
> Version rollover to 1.0.2-SNAPSHOT

- README.md
- build/build.sh
- demo/docker-compose.yml
- pom.xml
- src/main/resources/application.properties
Version rollover to 1.0.2 Release.
> Version rollover to 1.0.2 Release

- README.md
- build/Podmanfile
- build/README.md
- build/build.sh
- build/docker-compose.yml
- demo/Podmanfile-epid-verification
- demo/README.md
- enable_rhel_support.sh
Add EPID Verification Service support on RHEL
Signed-off-by: Shrikant Temburwar <shrikant.temburwar@intel.com>
> Add EPID Verification Service support on RHEL

- pom.xml
Spring boot version upgrade to the latest version.
> Spring boot version upgrade to the latest version

- pom.xml
> Upgrading Jackson library

- README.md
- build/README.md
- demo/README.md
> EPID README changes

- README.md
Update README for podman support
Signed-off-by: Shrikant Temburwar <shrikant.temburwar@intel.com>
> Update README for podman support

- NOTICE
- NOTICES/JAVAX-SERVLET-API
> Updating NOTICE files

- README.md
- demo/docker-compose.yml
- pom.xml
- src/main/resources/application.properties
Version rollover to 1.1.0 Release.
> Version rollover to 1.1.0 Release

- README.md
- demo/docker-compose.yml
- pom.xml
- src/main/resources/application.properties
Version rollover to 1.1.0.1-SNAPSHOT.
> Version rollover to 1.1.0.1-SNAPSHOT

- pom.xml
Upgrading dependencies to latest version.
> Upgrading dependencies to latest version

- README.md
- demo/docker-compose.yml
- pom.xml
- src/main/resources/application.properties
Version rollover to 1.1.3 SNAPSHOT.
> Version rollover to 1.1.3 SNAPSHOT

- pom.xml
Upgrading Snakeyaml and Jackson Databind.
> Upgrading Snakeyaml and Jackson Databind

- README.md
- demo/docker-compose.yml
- pom.xml
- src/main/resources/application.properties
Version rollover to 1.1.3 Release.
> Version rollover to 1.1.3 Release

- README.md
- demo/docker-compose.yml
- pom.xml
- src/main/resources/application.properties
Version rollover to 1.1.3.1 Release.
> Version rollover to 1.1.3.1 Release

- NOTICE
> Updating NOTICE file

- pom.xml
Upgrade dependencies to the latest version.
> Upgrade dependencies to the latest version

- pom.xml
Upgrading spring hateoas component.
> Upgrading spring hateoas component

- README.md
- demo/docker-compose.yml
- pom.xml
- src/main/resources/application.properties
Version rollover to 1.1.6 Release.
> Version rollover to 1.1.6 Release

- NOTICE
- README.md
- build/build.sh
- demo/README.md
- demo/docker-compose.yml
- download-cryptomaterials.sh
- pom.xml
- src/main/resources/application.properties
- src/test/resources/testng.xml
> V1.1.6 update

- pom.xml
Upgrading Guava to the latest version.
> Upgrading Guava to the latest version

- build/Dockerfile
- demo/Dockerfile-epid-verification
- pom.xml
Fixing Trivy scan issues and depenedency upgrades.
> Fixing Trivy scan issues and depenedency upgrades

- build/Dockerfile
- build/build.sh
- pom.xml
- src/main/java/org/fidoalliance/fdo/epid/verification/controllers/HealthController.java
- src/main/java/org/fidoalliance/fdo/epid/verification/controllers/ProofController.java
- src/main/java/org/fidoalliance/fdo/epid/verification/http/RequestInitializerInterceptor.java
- src/main/java/org/fidoalliance/fdo/epid/verification/model/requests/ProofRequest.java
Upgrading from Spring 2 to Spring 3
> Upgrading from Spring 2 to Spring 3

- README.md
- demo/docker-compose.yml
- pom.xml
- src/main/resources/application.properties
Version rollover to 1.1.8 Release.
> Version rollover to 1.1.8 Release

- SECURITY.md
> Adding Security Policy file

- README.md
- demo/docker-compose.yml
- pom.xml
- src/main/resources/application.properties
Version rollover to 1.1.9 Release.
> Version rollover to 1.1.9 Release
